Repository retaildevcrews/ngsa-asb, pull requests merged in 2021-09, with the labels that each got.

#2 Grafana Deployment and Dashboards for Azure monitor
  README.md
  monitoring/README.md
  monitoring/dashboards/ngsa-dev-model.json
  templates/grafana.yaml
Labels: size: M, Observe, CNCFMonitor

#3 Added Fluent Bit deploy instructions
  README.md
  templates/fluentbit/config-log.yaml
  templates/fluentbit/config.yaml
  templates/fluentbit/daemonset.yaml
  templates/fluentbit/role.yaml
Labels: Infa, DevOps, Setup

#5 Changed structure for enabling AutoGitops
  README.md
  deploy/bootstrap/cluster-baseline-settings/01-namespace.yaml
  deploy/bootstrap/cluster-baseline-settings/03-akv-secrets-store-csi.yaml
  deploy/bootstrap/cluster-baseline-settings/04-aad-pod-identity.yaml
  deploy/bootstrap/cluster-baseline-settings/05-kured.yaml
  deploy/bootstrap/ingress/01-namespace.yaml
  deploy/bootstrap/ingress/03-traefik.yaml
  deploy/bootstrap/kube-system/azm-agent-config.yaml
  deploy/ngsadev/config.json
  deploy/ngsadev/fluentbit/config-log.yaml
  deploy/ngsadev/fluentbit/config.yaml
  deploy/ngsadev/fluentbit/daemonset.yaml
  deploy/ngsadev/fluentbit/role.yaml
  deploy/ngsadev/monitoring/grafana.yaml
  docs/deployNgsaAgo.md
  docs/deployNgsaYaml.md
  gitops/README.md
  gitops/ngsa/namespace.yaml
  gitops/ngsa/ngsa-memory.yaml
  monitoring/README.md
  templates/flux.yaml
  templates/load-test.yaml
  templates/ngsa-memory.yaml
Labels: CI/CD, Documentation
