Repository retaildevcrews/ngsa-asb, pull requests merged in 2021-10, with the labels that each got.

#8 Added central preprod cluster
  deploy/ngsaprec/config.json
Labels: CI/CD

#9 Update templates
  deploy/ngsadev/config.json
  deploy/ngsaprec/config.json
Labels: Bug

#7 Configure ASB Prometheus
  README.md
  deploy/ngsadev/monitoring/01-namespace.yaml
  deploy/ngsadev/monitoring/02-prometheus.yaml
  deploy/ngsadev/monitoring/03-grafana.yaml
  monitoring/README.md
  templates/grafana.yaml
  templates/monitoring.yaml
  templates/prometheus.yaml
Labels: Observe, CNCFMonitor

#10 Update config.json to include loderunner
  deploy/ngsadev/config.json
  deploy/ngsaprec/config.json
Labels: CI-CD
