Repository retaildevcrews/ngsa-asb, pull requests merged in 2022-03, with the labels that each got.

#52 Deploy Grafana on Preprod clusters
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/01-grafana-config.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/02-grafana-config-datasources.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/04-grafana-pod-identity.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/05-grafana.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/dashboards/ngsa-az-monitor.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/dashboards/ngsa-prometheus.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/01-grafana-config.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/02-grafana-config-datasources.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/04-grafana-pod-identity.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-monitor.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-prometheus.yaml
  monitoring/README.md
  monitoring/dashboards/ngsa-pre-model.json
Labels: size: M, CNCFMonitor

#51 Bugfix/istio telemetry
  README.md
  deploy/dev-ngsa-asb-eastus/istio/istio-gateway.yaml
  deploy/dev-ngsa-asb-westus2/istio/istio-gateway.yaml
  deploy/pre-ngsa-asb-centralus/istio/istio-gateway.yaml
  deploy/pre-ngsa-asb-eastus/istio/istio-gateway.yaml
  deploy/pre-ngsa-asb-westus2/istio/istio-gateway.yaml
  templates/istio/istio-gateway.yaml
Labels: Bug, Infra

#54 Add loderunner to the Istio gateway template
  deploy/dev-ngsa-asb-eastus/istio/istio-gateway.yaml
  templates/istio/istio-gateway.yaml
Labels: CI/CD, DevOps, CI-CD

#56 Update Grafana Dashboards to support multi-region view
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-monitor.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/grafana/dashboards/ngsa-az-monitor.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/dashboards/ngsa-az-monitor.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-monitor.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/grafana/dashboards/ngsa-az-monitor.yaml
  monitoring/dashboards/ngsa-dev-model.json
  monitoring/dashboards/ngsa-pre-model.json
Labels: size: M, CNCFMonitor, DevOps
