Repository retaildevcrews/ngsa-asb, pull requests merged in 2022-09, with the labels that each got.

#106 NGSA-ASB Set-up for Clusters and Documentation
  README.md
  networking/hub-regionA.json
Labels: Bug, Documentation, DevOps, Setup, Infra

#115 Fixed Prometheus PVC issues
  deploy/bootstrap/flux-system/gotk-repo.yaml
  deploy/dev-bootstrap/flux-system/gotk-repo.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/02-prometheus.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/02-prometheus.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/02-prometheus.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/02-prometheus.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/02-prometheus.yaml
  docs/cloudshell.txt
  monitoring/README.md
  spikes/thanos/manifests/observee/prometheus/prometheus.yaml
  spikes/thanos/manifests/observer/prometheus/prometheus.yaml
  templates/monitoring/02-prometheus.yaml
Labels: Bug, size: M, CNCFMonitor

#120 Updated burst_header.wasm file to reflect fix for issue 997
  wasm/burst_header.wasm
Labels: Bug

#126 Update Memory and CPU for Flux deployments
  flux-init/init-dev/gotk-components-dev.yaml
  flux-init/init-preprod/gotk-components-pre.yaml
Labels: size: S, Infra

#128 Update Memory and CPU for Cluster baseline settings
  deploy/base/bootstrap/cluster-baseline-settings/03-akv-secrets-store-csi.yaml
  deploy/base/bootstrap/cluster-baseline-settings/05-kured.yaml
  deploy/bootstrap-dev/cluster-baseline-settings/04-aad-pod-identity.yaml
  deploy/bootstrap-pre/cluster-baseline-settings/04-aad-pod-identity.yaml
Labels: size: S, Infra

#124 Flux dashboards on dev and pre-prod
  deploy/dev-ngsa-asb-eastus/monitoring/02-prometheus.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/dashboards/flux-cluster.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/dashboards/flux-control-plane.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/kustomization.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/02-prometheus.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/grafana/05-grafana.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/grafana/dashboards/flux-cluster.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/grafana/dashboards/flux-control-plane.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/kustomization.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/02-prometheus.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/05-grafana.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/dashboards/flux-cluster.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/dashboards/flux-control-plane.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/kustomization.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/02-prometheus.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/dashboards/flux-cluster.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/dashboards/flux-control-plane.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/kustomization.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/02-prometheus.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/grafana/05-grafana.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/grafana/dashboards/flux-cluster.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/grafana/dashboards/flux-control-plane.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/kustomization.yaml
Labels: Observability
