Repository retaildevcrews/ngsa-asb, pull requests merged in 2022-07, with the labels that each got.

#75 Documented Fluentbit is sending random duplicate logs to Log Analytics
  README.md
Labels: Documentation, Observability, size: S

#80 Added crlf check
  .github/workflows/crlf-check.yaml
  docs/cosmos.md
Labels: CI/CD, Enhancement, size: S, DevOps

#82 Walkthrough of Cluster API bootstrap and pivot process
  .devcontainer/devcontainer.json
  .devcontainer/k3d.yaml
  .devcontainer/on-create.sh
  .devcontainer/post-install.sh
  .gitignore
  Makefile
  spikes/cluster-api/README.md
  spikes/cluster-api/diagrams/out/ClusterAPI-Bootstrap-Pivot.svg
  spikes/cluster-api/diagrams/source/clusterapi-bootstrap-pivot.puml
Labels: SPIKE

#83 Add Checkov VS code Task to Codespaces and populate a summary section.
  .gitignore
  .vscode/tasks.json
  README.md
Labels: Bug, DevExperience, Infa, CI-CD

#84 Harbor Spike
  spikes/harbor/README.md
  spikes/harbor/gen-multi-domain-certs.bash
  spikes/harbor/harbor-virtual-svc.yaml
  spikes/harbor/harbor.yml
  spikes/harbor/helm-values.yaml
Labels: SPIKE, CI-CD
