Repository retaildevcrews/ngsa-asb, pull requests merged in 2022-10, with the labels that each got.

#135 Flux directory sturctuure documentation
  README.md
  docs/FluxDirStructure.md
Labels: Documentation

#140 Kustomize optimization for Istio
  deploy/base/apps/istio/istio-gateway.yaml
  deploy/base/apps/istio/istio-ingress.yaml
  deploy/base/apps/istio/istio-pod-identity-config.yaml
  deploy/base/apps/istio/kustomization.yaml
  deploy/dev-ngsa-asb-eastus/istio/istio-gateway.yaml
  deploy/dev-ngsa-asb-eastus/istio/istio-ingress.yaml
  deploy/dev-ngsa-asb-eastus/istio/istio-pod-identity-config.yaml
  deploy/dev-ngsa-asb-eastus/istio/kustomization.yaml
  deploy/dev-ngsa-asb-westus2/istio/istio-gateway.yaml
  deploy/dev-ngsa-asb-westus2/istio/istio-ingress.yaml
  deploy/dev-ngsa-asb-westus2/istio/istio-pod-identity-config.yaml
  deploy/dev-ngsa-asb-westus2/istio/kustomization.yaml
  deploy/pre-ngsa-asb-centralus/istio/istio-gateway.yaml
  deploy/pre-ngsa-asb-centralus/istio/istio-ingress.yaml
  deploy/pre-ngsa-asb-centralus/istio/kustomization.yaml
  deploy/pre-ngsa-asb-eastus/istio/istio-gateway.yaml
  deploy/pre-ngsa-asb-eastus/istio/istio-ingress.yaml
  deploy/pre-ngsa-asb-eastus/istio/istio-pod-identity-config.yaml
  deploy/pre-ngsa-asb-eastus/istio/kustomization.yaml
  deploy/pre-ngsa-asb-westus2/istio/istio-gateway.yaml
  deploy/pre-ngsa-asb-westus2/istio/istio-pod-identity-config.yaml
  deploy/pre-ngsa-asb-westus2/istio/kustomization.yaml
Labels: DevOps

#146 Added burst namespace for kustomization
  deploy/dev-ngsa-asb-westus2/burst/kustomization.yaml
  deploy/dev-ngsa-asb-westus2/burst/namespace.yaml
Labels: Bug

#147 Added Azure Front Door setup instructions
  README.md
  docs/deployFrontDoor.md
  spikes/front-door/setup-front-door.md
  spikes/front-door/setup-frontdoor.sh
Labels: DesignReview, Documentation, Pri2, size: L, Infra

#132 Automated Infrastructure Deployment Script
  .gitignore
  README.md
  cluster/cluster-stamp-additional.json
  cluster/cluster-stamp.json
  networking/hub-default.json
  networking/hub-regionA.json
  networking/spoke-default.json
  saveenv.sh
  scripts/clusterCreation/1-CheckPrerequisites.sh
  scripts/clusterCreation/2-CreateHub.sh
  scripts/clusterCreation/3-AttachSpokeAndClusterToHub.sh
  spikes/cilium/cluster-stamp.json
  spikes/cilium/hub-regionA.json
Labels: Infra

#148 Instructions to disable cosmos keys, enable RBAC to connect to CosmosDB
  spikes/cosmos-rbac/rbac_cosmos_in_aks.md
Labels: Pri2, SPIKE, size: M
