Repository retaildevcrews/ngsa-asb, pull requests merged in 2022-01, with the labels that each got.

#34 Use common networking between multiple clusters
  README.md
  cluster/cluster-stamp-additional.json
  cluster/cluster-stamp.json
  deploy/bootstrap/ngsa/namespace.yaml
  deploy/ngsadev/istio/03-istio-ingress.yaml
  deploy/ngsaprec/istio/03-istio-ingress.yaml
  docs/HackGuide.md
  docs/cloudshell.txt
  docs/cosmos.md
  docs/deployAdditionalCluster.md
  docs/deployNgsaYaml.md
  monitoring/README.md
  networking/hub-default.json
  networking/hub-regionA.json
  networking/spoke-default.json
  saveenv.sh
  templates/fluentbit/config-log.yaml
  templates/istio/istio-gateway.yaml
  templates/istio/istio-ingress.yaml
  templates/istio/istio-pod-identity.yaml
  templates/load-test.yaml
  templates/loderunner.yaml
  templates/monitoring/01-monitoring.yaml
  templates/monitoring/02-grafana-pod-identity.yaml
  templates/monitoring/03-grafana-aad.yaml
  templates/monitoring/04-prometheus.yaml
  templates/monitoring/grafana.yaml
  templates/ngsa/ngsa-cosmos.yaml
  templates/ngsa/ngsa-java.yaml
  templates/ngsa/ngsa-memory.yaml
  templates/ngsa/ngsa-pod-identity.yaml
Labels: size: L

#35 Subdomain multicluster
  README.md
  cluster/cluster-stamp-additional.json
  cluster/cluster-stamp.json
  deploy/ngsadev/istio/istio-gateway.yaml
  deploy/ngsadev/istio/istio-ingress.yaml
  deploy/ngsadev/monitoring/03-grafana.yaml
  deploy/ngsaprec/istio/istio-ingress.yaml
  docs/cosmos.md
  docs/deployAdditionalCluster.md
  docs/deployNgsaYaml.md
  monitoring/README.md
  networking/spoke-default.json
  saveenv.sh
  templates/istio/istio-gateway.yaml
  templates/loderunner.yaml
  templates/monitoring/03-grafana-aad.yaml
  templates/monitoring/grafana.yaml
  templates/ngsa/ngsa-cosmos.yaml
  templates/ngsa/ngsa-java.yaml
  templates/ngsa/ngsa-memory.yaml
Labels: size: M

#38 Fixed autogitops for dev clusters
  deploy/dev-ngsa-asb-eastus/config.json
  deploy/dev-ngsa-asb-eastus/loderunner/loderunner.yaml
  deploy/dev-ngsa-asb-eastus/ngsa/ngsa-cosmos.yaml
  deploy/dev-ngsa-asb-eastus/ngsa/ngsa-java.yaml
  deploy/dev-ngsa-asb-eastus/ngsa/ngsa-memory.yaml
  deploy/dev-ngsa-asb-westus2/config.json
  deploy/dev-ngsa-asb-westus2/loderunner/loderunner.yaml
  deploy/dev-ngsa-asb-westus2/ngsa/ngsa-cosmos.yaml
  deploy/dev-ngsa-asb-westus2/ngsa/ngsa-java.yaml
  deploy/dev-ngsa-asb-westus2/ngsa/ngsa-memory.yaml
Labels: size: S

#39 Added instructions to update Hub Firewall Policy Network Rules
  docs/deployAdditionalCluster.md
Labels: Bug, Documentation, size: S, Infra

#40 Decomission old asb dev cluster config
  deploy/ngsadev/config.json
  deploy/ngsadev/fluentbit/config-log.yaml
  deploy/ngsadev/fluentbit/config.yaml
  deploy/ngsadev/fluentbit/daemonset.yaml
  deploy/ngsadev/fluentbit/role.yaml
  deploy/ngsadev/istio/istio-gateway.yaml
  deploy/ngsadev/istio/istio-ingress.yaml
  deploy/ngsadev/istio/istio-pod-identity-config.yaml
  deploy/ngsadev/loderunner/dev/loderunner/loderunner.yaml
  deploy/ngsadev/loderunner/namespace.yaml
  deploy/ngsadev/monitoring/01-namespace.yaml
  deploy/ngsadev/monitoring/02-prometheus.yaml
  deploy/ngsadev/monitoring/03-grafana.yaml
  deploy/ngsadev/monitoring/04-grafana-pod-identity.yaml
  deploy/ngsadev/ngsa/dev/ngsa-envoy-filter.yaml
  deploy/ngsadev/ngsa/dev/ngsa-java/ngsa-java.yaml
  deploy/ngsadev/ngsa/dev/ngsa/ngsa-cosmos.yaml
  deploy/ngsadev/ngsa/dev/ngsa/ngsa-memory.yaml
  deploy/ngsadev/ngsa/namespace.yaml
Labels: size: S
