Repository retaildevcrews/ngsa-asb, pull requests merged in 2022-08, with the labels that each got.

#86 Added --quiet and --compact arguments to Checkov Scan task
  .vscode/tasks.json
Labels: Bug, CI/CD

#87 Add documentation for Azure resource locks
  README.md
Labels: Documentation

#94 Document how to disable WAF-config
  README.md
  cluster/cluster-stamp-additional.json
  cluster/cluster-stamp.json
  docs/disableWAFconfig.md
Labels: Documentation, size: S, Infa

#93 Added Spike Instructions on how to setup Cluster API with Cilium
  spikes/cluster-api-cilium/README.md
  spikes/cluster-api-cilium/manifests/infrastructure.cluster.x-k8s.io_azuremanagedcontrolplanes.yaml
  spikes/cluster-api-cilium/manifests/workload-cluster01.yaml
Labels: size: S, Infra

#98 Reduce app gateway alert uptime threshold
  monitoring/README.md
  monitoring/alerts/metricsAlerts/dev/asb-dev-eastus-AppEndpointDown.json
  monitoring/alerts/metricsAlerts/dev/asb-dev-westus2-AppEndpointDown.json
  monitoring/alerts/metricsAlerts/pre/asb-pre-centralus-AppEndpointDown.json
  monitoring/alerts/metricsAlerts/pre/asb-pre-eastus-AppEndpointDown.json
  monitoring/alerts/metricsAlerts/pre/asb-pre-westus2-AppEndpointDown.json
Labels: Observe

#104 Thanos Spike
  .gitignore
  spikes/thanos/README.md
  spikes/thanos/manifests/observee/ngsa/loderunner.yaml
  spikes/thanos/manifests/observee/ngsa/ngsa.yaml
  spikes/thanos/manifests/observee/prometheus/prometheus.yaml
  spikes/thanos/manifests/observee/thanos/thanos-compactor.yaml
  spikes/thanos/manifests/observee/thanos/thanos-querier.yaml
  spikes/thanos/manifests/observee/thanos/thanos-store.yaml
  spikes/thanos/manifests/observer/grafana/grafana.yaml
  spikes/thanos/manifests/observer/grafana/ngsa.json
  spikes/thanos/manifests/observer/ngsa/loderunner.yaml
  spikes/thanos/manifests/observer/ngsa/ngsa.yaml
  spikes/thanos/manifests/observer/prometheus/prometheus.yaml
  spikes/thanos/manifests/observer/thanos/thanos-compactor.yaml
  spikes/thanos/manifests/observer/thanos/thanos-querier.yaml
  spikes/thanos/manifests/observer/thanos/thanos-store.yaml
  spikes/thanos/manifests/template/thanos-storage-config.yaml.tmpl
Labels: size: L, Observe

#105 Deploy harbor on EastUS Dev Cluster
  deploy/dev-ngsa-asb-eastus/istio/istio-gateway.yaml
  spikes/harbor/README.md
  spikes/harbor/harbor-virtual-svc.yaml
  spikes/harbor/harborflows.md
  spikes/harbor/helm-values.yaml
Labels: SPIKE, DevOps

#109 Added loderunner endpoint to preprod centralus ingress gateway
  deploy/pre-ngsa-asb-centralus/istio/istio-gateway.yaml
Labels: CI/CD, CI-CD
