Repository retaildevcrews/ngsa-asb, pull requests merged in 2022-11, with the labels that each got.

#149 updated fluentbit configmaps
  deploy/dev-ngsa-asb-eastus/fluentbit/kustomization.yaml
  deploy/dev-ngsa-asb-westus2/fluentbit/kustomization.yaml
  deploy/pre-ngsa-asb-centralus/fluentbit/kustomization.yaml
  deploy/pre-ngsa-asb-eastus/fluentbit/kustomization.yaml
  deploy/pre-ngsa-asb-westus2/fluentbit/kustomization.yaml
Labels: Bug, Pri1, CI-CD

#142 Firewall State Automation Implementation
  docs/Firewall-Automation.md
  docs/assets/Firewall-Automation/AccessControlforManagedIdentitywithAddRoleAssignemnt.png
  docs/assets/Firewall-Automation/RolesForManagedIdentity.png
  docs/assets/Firewall-Automation/automationResourceGroupListPortal.png
  docs/assets/Firewall-Automation/createAutmationAccountSchedule1Portal.png
  docs/assets/Firewall-Automation/createAutmationRunbook1Portal.png
  docs/assets/Firewall-Automation/createAutmationRunbook2Portal.png
  docs/assets/Firewall-Automation/createAutomationAccount1Portal.png
  docs/assets/Firewall-Automation/createAutomationAccount2Portal.png
  docs/assets/Firewall-Automation/createAutomatioonAccountPortal.png
  docs/assets/Firewall-Automation/createResourceGroup1Portal.png
  docs/assets/Firewall-Automation/createRunbookSchedule1Portal.png
  docs/assets/Firewall-Automation/createUserAssginedManagedIdentityPortal.png
  docs/assets/Firewall-Automation/createUserAssignedManagedIdentity1Portal.png
  docs/assets/Firewall-Automation/editRunbookScheduleLinked1Portal.png
  docs/assets/Firewall-Automation/endAutomationScheduleLinked1Portal.png
  docs/assets/Firewall-Automation/listOfResourcesInResourceGroup.png
  docs/assets/Firewall-Automation/managedIdentityMemberPick1.png
  docs/assets/Firewall-Automation/managedIdentityMemberPick2.png
  docs/assets/Firewall-Automation/managedIdentityRoleSelection.png
  scripts/Firewall-Automation/Firewall-Automation-Infrastructure-Variables.sh
  scripts/Firewall-Automation/Firewall-Automation-Infrastructure.sh
  scripts/Firewall-Automation/Firewall-Automation-Runbook.ps1
  scripts/Firewall-Automation/Firewall-Automation-Schedule-Creation.ps1
Labels: Documentation, UserStory

#151 Updated ARM files and script to include westus3 and northcentralus
  cluster/cluster-stamp-additional.json
  cluster/cluster-stamp.json
  networking/hub-default.json
  networking/hub-regionA.json
  networking/spoke-default.json
  scripts/clusterCreation/2-CreateHub.sh
  spikes/cilium/cluster-stamp.json
  spikes/cilium/hub-regionA.json
Labels: Infra, Infrastructure

#155 Burst Headers Issue Fix
  deploy/dev-ngsa-asb-westus2/burst/burst-flux-kustomization.yaml
Labels: Bug
