Repository retaildevcrews/ngsa-asb, pull requests merged in 2022-12, with the labels that each got.

#152 Updated Readme.md for firewall and permissions
  README.md
  deploy/dev-ngsa-asb-eastus/ngsa/dev/ngsa/ngsa-memory.yaml
Labels: CI/CD, Documentation, Enhancement, Infra

#159 Firewall Automation Setup and Dev Experience Improvement
  .gitignore
  docs/Firewall-Automation.md
  scripts/Firewall-Automation/Firewall-Automation-Infrastructure-Variables-Template.txt
  scripts/Firewall-Automation/Firewall-Automation-Infrastructure.sh
  scripts/Firewall-Automation/Firewall-Automation-Runbook.ps1
  scripts/Firewall-Automation/Firewall-Automation-Schedule-Creation.ps1
  scripts/Firewall-Automation/Firewall-Automation-SetSystemAssignedIdentity.ps1
Labels: DevExperience, Documentation, size: L, Infra, Infrastructure

#160 Update Harbor URL and Integrate AAD via OIDC
  spikes/harbor/README.md
  spikes/harbor/harbor-virtual-svc.yaml
  spikes/harbor/helm-values.yaml
Labels: Infra

#165 Added spike instructions for image automation
  spikes/image-versioning/imageAutomation.md
  spikes/image-versioning/ngsa/ngsa-memory.yaml
Labels: Infra

#166 Added documentation on how to renew ssl certs
  docs/renewCertificates.md
Labels: Infra
