Repository retaildevcrews/ngsa-asb, pull requests merged in 2022-04, with the labels that each got.

#59 Updated NGSA-ASB docs
  README.md
  docs/deployNgsaAgo.md
  docs/deployNgsaYaml.md
Labels: CI/CD, Documentation, size: S

#60 FirewallPolicy, ruleCollectionGroup for *-dev.cse.ms
  networking/hub-regionA.json
Labels: Testing:Load, Infa

#61 Blocked network traffic Grafana dashboard
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-blocked-traffic.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-blocked-traffic.yaml
  monitoring/README.md
Labels: Observe

#62 Split Az Monitor Dashboards
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-monitor-perf.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-monitor-rel.yaml
  deploy/dev-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-monitor.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/grafana/05-grafana.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/grafana/dashboards/ngsa-az-monitor-perf.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/grafana/dashboards/ngsa-az-monitor-rel.yaml
  deploy/dev-ngsa-asb-westus2/monitoring/grafana/dashboards/ngsa-az-monitor.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/05-grafana.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/dashboards/ngsa-az-monitor-perf.yaml
  deploy/pre-ngsa-asb-centralus/monitoring/grafana/dashboards/ngsa-az-monitor-rel.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/05-grafana.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-monitor-perf.yaml
  deploy/pre-ngsa-asb-eastus/monitoring/grafana/dashboards/ngsa-az-monitor-rel.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/grafana/03-grafana-config-dashboards.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/grafana/05-grafana.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/grafana/dashboards/ngsa-az-monitor-perf.yaml
  deploy/pre-ngsa-asb-westus2/monitoring/grafana/dashboards/ngsa-az-monitor-rel.yaml
Labels: CNCFMonitor
