Repository retaildevcrews/ngsa-asb, pull requests merged in 2023-02, with the labels that each got.

#177 Documentation for Diagrams
  docs/Automation-Observability.md
  docs/assets/Automation-Dashboard/DashboardForAutomation.png
  docs/assets/Automation-Dashboard/grafana-Logs.png
  docs/assets/Automation-Dashboard/grafana-TimeSeries.png
  docs/assets/Automation-Dashboard/grafana-Timeline.png
  docs/assets/Automation-Dashboard/grafanaJobs-Completed.png
  docs/assets/Automation-Dashboard/grafanaJobs-Created.png
  docs/assets/Automation-Dashboard/grafanaJobs-Errors.png
  docs/assets/Automation-Dashboard/grafanaLogIn.png
Labels: Documentation

#180 Migrate firewall startup/shutdown job to bicep based deployment.
  scripts/ResourceAutomation/README.md
  scripts/ResourceAutomation/automation.bicep
  scripts/ResourceAutomation/automation.parameters.json
  scripts/ResourceAutomation/automationAccount.bicep
  scripts/ResourceAutomation/runbooks/firewall_startstop.ps1
Labels: Infrastructure

#181 Updated firewall Schedule name
  scripts/ResourceAutomation/automationAccount.bicep
Labels: Bug, Infrastructure

#182 Update job schedule names to new unique ones
  scripts/ResourceAutomation/automationAccount.bicep
Labels: Bug, Infrastructure

#183 ArgoCD spike implementation
  spikes/argo-cd/README.md
  spikes/argo-cd/deploy/ngsa.yaml
  spikes/argo-cd/manifests/application-set-sample.yaml
  spikes/argo-cd/manifests/argo-ngsa-app.yaml
Labels: SPIKE

#184 Deprecate automation powershell scripts and documentation
  docs/Aks-Cluster-Automation.md
  docs/App-Gateway-Automation.md
  docs/Firewall-Automation.md
  docs/assets/Firewall-Automation/AccessControlforManagedIdentitywithAddRoleAssignemnt.png
  docs/assets/Firewall-Automation/RolesForManagedIdentity.png
  docs/assets/Firewall-Automation/automationResourceGroupListPortal.png
  docs/assets/Firewall-Automation/createAutmationAccountSchedule1Portal.png
  docs/assets/Firewall-Automation/createAutmationRunbook1Portal.png
  docs/assets/Firewall-Automation/createAutmationRunbook2Portal.png
  docs/assets/Firewall-Automation/createAutomationAccount1Portal.png
  docs/assets/Firewall-Automation/createAutomationAccount2Portal.png
  docs/assets/Firewall-Automation/createAutomatioonAccountPortal.png
  docs/assets/Firewall-Automation/createResourceGroup1Portal.png
  docs/assets/Firewall-Automation/createRunbookSchedule1Portal.png
  docs/assets/Firewall-Automation/createUserAssginedManagedIdentityPortal.png
  docs/assets/Firewall-Automation/createUserAssignedManagedIdentity1Portal.png
  docs/assets/Firewall-Automation/editRunbookScheduleLinked1Portal.png
  docs/assets/Firewall-Automation/endAutomationScheduleLinked1Portal.png
  docs/assets/Firewall-Automation/listOfResourcesInResourceGroup.png
  docs/assets/Firewall-Automation/managedIdentityMemberPick1.png
  docs/assets/Firewall-Automation/managedIdentityMemberPick2.png
  docs/assets/Firewall-Automation/managedIdentityRoleSelection.png
  scripts/Aks-Cluster-Automation/Aks-Cluster-Automation-Infrastructure-Variables-Template.txt
  scripts/Aks-Cluster-Automation/Aks-Cluster-Automation-Infrastructure.sh
  scripts/Aks-Cluster-Automation/Aks-Cluster-Automation-Runbook.ps1
  scripts/Aks-Cluster-Automation/Aks-Cluster-Automation-Schedule-Creation.ps1
  scripts/App-Gateway-Automation/App-Gateway-Automation-Infrastructure-Variables-Template.txt
  scripts/App-Gateway-Automation/App-Gateway-Automation-Infrastructure.sh
  scripts/App-Gateway-Automation/App-Gateway-Automation-Runbook.ps1
  scripts/App-Gateway-Automation/App-Gateway-Automation-Schedule-Creation.ps1
  scripts/Firewall-Automation/Firewall-Automation-Infrastructure-Variables-Template.txt
  scripts/Firewall-Automation/Firewall-Automation-Infrastructure.sh
  scripts/Firewall-Automation/Firewall-Automation-Runbook.ps1
  scripts/Firewall-Automation/Firewall-Automation-Schedule-Creation.ps1
  scripts/Firewall-Automation/Firewall-Automation-SetSystemAssignedIdentity.ps1
Labels: CI-CD
